import casesClientData from "@/data/cases-client.json";
import type { UAPCase } from "./types";

/**
 * Slim corpus for CLIENT components (WorldMap, DataExplorer, KpiCard).
 *
 * Identical to `cases` from lib/data.ts but WITHOUT the heavy narrative fields
 * (`whatHappened` / `whyMatters` + their `_en`), which no client visualization
 * renders. Those four fields are ~68 % of cases.json (~2.6 MB); importing the
 * full corpus into a client component shipped all of it to the browser and was
 * the dominant cause of the home LCP (11 s on Slow-4G) and JS bloat.
 *
 * Generated by scripts/build-cases.mjs (gitignored artifact). The cast to
 * UAPCase[] is sound because the dropped fields are optional in UAPCase.
 * SERVER components must keep importing the full `cases` from lib/data.ts.
 */
export const casesClient = casesClientData as UAPCase[];
